//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property
{
    using System;
    using System.Collections.Generic;
    
    public partial class property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public property()
        {
            this.offers = new HashSet<offer>();
            this.ratings = new HashSet<rating>();
            this.referproperties = new HashSet<referproperty>();
        }
    
        public int property_id { get; set; }
        public string property_type { get; set; }
        public string property_location { get; set; }
        public Nullable<int> property_price { get; set; }
        public Nullable<int> property_bed { get; set; }
        public Nullable<int> property_washroom { get; set; }
        public Nullable<int> property_size { get; set; }
        public Nullable<int> account_id { get; set; }
        public byte[] property_image { get; set; }
        public string property_image_type { get; set; }
        public Nullable<int> company_id { get; set; }
    
        public virtual aacount aacount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<offer> offers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rating> ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<referproperty> referproperties { get; set; }
    }
}
